pipeline {
  agent { label 'linux' }
  stages {
    stage('build') {
      parallel {
        stage('build-windows') {
          agent { label 'windows' }
          steps {
            bat 'SET'
          }
        }
        stage('build-linux') {
          steps {
            sh 'echo hi'
          }
        }
      }
    }
  }
}
